{
 "title": "node_exporter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[$__rate_interval]) * 100",
     "legendFormat": "CPU{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU LA",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{job=\"node-exporter\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "node_load5{job=\"node-exporter\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "node_load15{job=\"node-exporter\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory Free ,%",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes{job=\"node-exporter\"} / node_memory_MemTotal_bytes{job=\"node-exporter\"} ) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Free space",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{job=\"node-exporter\", mountpoint=\"/\"} / 1073741824",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}